name: Release components package
'on':
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        shell: bash
        run: >-
          pnpm publish packages/components --access public --no-git-checks
          --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
