name: Automated Tagging
on:
  push:
    branches: [ master ]

permissions:
  contents: write 

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create & push tag
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          TAG="v${GITHUB_RUN_NUMBER}"
          git tag -a "$TAG" -m "Release $TAG"
          # ensure pushes use the token
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
          git push origin "$TAG"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: Description of the changes in this release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}